### PR TITLE
fix: replace hostname with host in admin config

### LINKED ISSUE #432: host versus hostname: need consistency
the `admin:` section and `apiEndpoints:` use `host:` versus `hostname:` should pick one

- [ ] update generators
- [ ] update docs
- [ ] update CLI
- [ ] update tests

### PR DESCRIPTION
**Pull request by ravikp7**
- improves consistency with apiEndpoints config
- generators now use host in admin config
- hostname is still supported, but warning is shown

fixes #432

### CODE REVIEW

File: bin/eg-generator.js [hunk 1]
```diff
@@ -71,10 +71,10 @@ module.exports = class EgGenerator extends Generator {
       baseURL = systemConfig.cli.url;
     } else if (gatewayConfig && gatewayConfig.admin) {
       const adminConfig = gatewayConfig.admin;
-      const hostname = adminConfig.hostname || 'localhost';
+      const host = adminConfig.host || 'localhost';
```
Comment (XVincentX) [inline bin/eg-generator.js]: You need also to try to grab the property from the old property that we're not going to deprecate.
```suggestion
      const host = adminConfig.host || adminConfig.hostname || 'localhost';
```

If would be great if you could also delete the default value `localhost` and put it in the default value of the JSON Schema file.

File: lib/config/schemas/gateway.config.json [hunk 2]
```diff
@@ -107,6 +107,9 @@
         "port": {
           "type": "number"
         },
+        "host": {
+          "type": "string"
+        },
```
Comment (XVincentX) [inline lib/config/schemas/gateway.config.json]: You should update the JSON Schema to make sure only one of the two properties are present (host or hostname)

File: lib/rest/index.js [hunk 3]
```diff
@@ -9,7 +9,11 @@ module.exports = function ({ plugins, config } = {}) {
     logger.verbose('Admin server is not configured, launch canceled');
     return;
   }
-  cfg.admin.hostname = cfg.admin.hostname || 'localhost';
+  if (cfg.admin.hostname) {
+    // eslint-disable-next-line no-console
+    console.log('Warning! use of hostname is depracated in admin section, use host instead');
```
Comment (XVincentX) [inline lib/rest/index.js]: Do not use `console.log`, use the `logger object`

```suggestion
    logger.warn('Warning! use of hostname is depracated in admin section, use host instead');
```

File: lib/config/schemas/gateway.config.json (hunk 2 above)
Comment (ravikp7) [reply lib/config/schemas/gateway.config.json]: - If we remove `hostname` from here, will it still be able to support old configurations?
- Btw, what's the purpose of this JSON Schema? I'm not sure of this

**Comment by ravikp7** [comment]
I'm not sure of where to put tests or what to test for the changes made in this PR.
Can you please guide me on this?

File: lib/config/schemas/gateway.config.json (hunk 2 above)
Comment (XVincentX) [reply lib/config/schemas/gateway.config.json]: We're not going to remove it, we're going to put a constraint so that the user will only use `host` or `hostname`, using the JSON Schema.

The JSON Schema is basically a JSON file telling how an object should look like, so that you can validate it and make actions.

For instance, if I declare a JSON Schema like this:

```json
{
  "$id": "http://express-gateway.io/models/users.json",
  "type": "object",
  "properties": {
    "firstname": {
      "type": "string"
    },
    "lastname": {
      "type": "string"
    },
    "username": {
      "type": "string"
    },
    "email": {
      "type": "string",
      "format": "email"
    },
    "redirectUri": {
      "type": "string",
      "format": "uri"
    }
  },
  "required": [
    "username",
    "firstname",
    "lastname"
  ]
}
```

Then the object passing the validation will have al least     "username","firstname", "lastname"  properties defined and they're a string.

We use that to validate the configuration files `gateway.config.yml` and `system.config.yml`

Comment (ravikp7) [reply lib/config/schemas/gateway.config.json]: Got it, thanks!

File: lib/rest/index.js [hunk 4]
```diff
@@ -9,7 +9,11 @@ module.exports = function ({ plugins, config } = {}) {
...
+  }
+  cfg.admin.host = cfg.admin.hostname || cfg.admin.host || 'localhost';
```
Comment (XVincentX) [inline lib/rest/index.js]: Let's remove the default value and put it in the JSON Schema

```suggestion
  cfg.admin.host = cfg.admin.hostname || cfg.admin.host;
```

**Comment by XVincentX** [comment]
> I'm not sure of where to put tests or what to test for the changes made in this PR.

Good point. Let's first make sure the code is ready and then CodeCov will guide us in the part that needs to be covered.

It's not exactly that mandatory to test this stuff (I can live with it) but it'd be great to onboard you appropriately :)

Keep up the good work!

File: lib/rest/index.js (hunk 4 above)
Comment (ravikp7) [reply lib/rest/index.js]: If we remove `localhost` default value from here, then `28 tests` are breaking.
- One of them is https://github.com/ExpressGateway/express-gateway/blob/8d4e9646e795538ee2abf272b190cabff0ae7568/test/rest-api/api-endpoint.test.js#L24
- I think, in these tests, the `yaml config` is made up directly from object defined there and `host` is missing there, so it relies on this default value in the `lib/rest/index.js` file and not on the JSON schema default value.
___
If that's the case, then we've two options:
- Add `host` in the config objects for all the failing tests
-  or Leave this default value as it is here

Please let me know if I missed something

File: lib/config/schemas/gateway.config.json (hunk 2 above)
Comment (XVincentX) [reply lib/config/schemas/gateway.config.json]: Once addressed, do not forget to mark the conversation as resolved. This helps the reviews ;)

image

File: lib/rest/index.js (hunk 4 above)
Comment (XVincentX) [reply lib/rest/index.js]: @ravikp7 The reason is a wrong JSON Schema. It can be tricky sometimes to modify it correctly so I went ahead and modified it for you. See the changes at ca50b189fb7fa1f961bbf0021194d52a6cdd9e47

Basically what is needed is to declare both property in the schema, and then use the `oneOf` feature to specify that only one of the two is required.

I've also modified the order — as we want to give the new property `host` precedence over `hostname`

**Comment by XVincentX** [comment]
I also went ahead and checked what's up with the tests and the untested part do not concern this PR. Good to go! 🚀
